export const START_FETCHING_AIRCRAFTS = 'START_FETCHING_AIRCRAFTS';
export const ERROR_FETCHING_AIRCRAFTS = 'ERROR_FETCHING_AIRCRAFTS';
export const SUCCESS_FETCHING_AIRCRAFTS = 'SUCCESS_FETCHING_AIRCRAFTS';

export const START_FETCHING_AIRCRAFT = 'START_FETCHING_AIRCRAFT';
export const ERROR_FETCHING_AIRCRAFT = 'ERROR_FETCHING_AIRCRAFT';
export const SUCCESS_FETCHING_AIRCRAFT = 'SUCCESS_FETCHING_AIRCRAFT';